### ISSUE TITLE
[BUG] [Chartmaker] Lanes become blue at Alpha 1 even when the Lane Color is set to #FFFFFF

### ISSUE THREAD

**Issue by YukiNeko27** [FFF40/JANOARG#16]
Image 1:
![JANOARG  2024-12-15 - 01-33-39](https://github.com/user-attachments/assets/de38d9a0-5e20-45eb-8535-91815841a1a0)

Image 2:
![JANOARG  2024-12-15 - 01-37-41](https://github.com/user-attachments/assets/1fd53536-e28f-455b-88b0-1f46ebb4afb0)

**Comment by YukiNeko27** [comment]
Tested more things out, and found out that ONLY Lane Color turns blue at hexcolor FFFFFF.

Normal, Catch and Hold Tail colors become pure white when set to hexcolor FFFFFF

**Comment by ducdat0507** [comment]
Should be fixed now
