### ISSUE TITLE
Lane's underside being blank?

### ISSUE THREAD

**Issue by YukiNeko27** [FFF40/JANOARG#20]
![Chartmaker  2024-12-21 - 23-56-04](https://github.com/user-attachments/assets/b93e20c9-5aec-4267-b20e-2aaae6ae73eb)

![Chartmaker  2024-12-21 - 23-56-09](https://github.com/user-attachments/assets/d79eafa4-fd72-48b6-9fbe-588cf4003bc0)

Top picture is how the lane is normally, and the bottom picture is the lane's underside.

Why is the underside suddenly invisible? It wasn't like that in Preview 4.

**Comment by YukiNeko27** [comment]
Supposed to look like this: (screenshot from a Preview 4 render)
![image](https://github.com/user-attachments/assets/cc660e0e-da8d-41aa-8be6-3f0e970ac024)

**Comment by ducdat0507** [comment]
Should be fixed now
