### ISSUE TITLE
Make smaller windowed tabs movable in chartmaker.

### ISSUE THREAD

**Issue by 404Foxtrot** [FFF40/JANOARG#3]
Just as the title says; It would be really useful if smaller windowed tabs (such as Chartmaker Manual or New Chart) could be moved on the other sides of screen and such. So that they don't obstruct stuff that you are working with.

**Comment by BashhScriptKid** [comment]
Do you meant child windows should have their own window rather than the in-app's virtual ones?

**Comment by Lorzitz** [comment]
Yes, probably that.

**Comment by RKevo** [comment]
> Do you meant child windows should have their own window rather than the in-app's virtual ones?

or one could also make the in-editor tab movable
