### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by Cheesescodeiscool** [FFF40/JANOARG#4]
You have to enable the compatibility on Android 14 I think.

I have Google pixel 7a

**Comment by ducdat0507** [comment]
I need more info, can you describe what happened?

**Comment by Cheesescodeiscool** [comment]
It won't install because the version is too early. It also doesn't support arm 64 but architecture v8. (Should be backwards compatible tho)

**Comment by Cheesescodeiscool** [comment]
When I build from scratch and made it compatible with my phone it looks like this 

Look in #skillshare

**Comment by ducdat0507** [comment]
Your build didn't work because there's no songs in the project
(I excluded songs from the repo so artists won't complain at me about copyright stuff)
