### ISSUE TITLE
So Many Timeline Suggestions

### ISSUE THREAD

**Issue by Cheesescodeiscool** [FFF40/JANOARG#7]
These suggestions mainly concern the timeline, which is a bit frustrating to use, but hopefully, these conveniences could be added. 
* When Clicking on the timeline with the note selected, adding the note will make it go back to the cursor. (I keep on misplacing notes)
* Could drag notes position in the timeline
* Right-click to delete
* Have hold move dynamically, like the lanes.
* Shift left-click on the note to select it.
* Could zoom in and zoom out on the timeline
* Could also use the preview as a way to add notes while having a grid (kind of like arcaea)
* Add cos and tan and have a custom equation for how the line sways.
* Could drag the lane notes on the left to move it

**Comment by ducdat0507** [comment]
Please make one suggestion per issue, so I can keep track of individual suggestions
